# Data Directories:
DATA_PATH: "../data"
RAW_PATH: "1_raw"
PREP_PATH: "2_preprocessed"
MODELS_PATH: "3_models"
PRED_PATH: "4_predictions"
RES_PATH: "5_results"
MLFLOW_PATH: "6_mlflow/mlruns"

# Mlflow config
MLFLOW_URI: "http://localhost:5005"

# ML FLOW
EXPERIMENT: "Benchmark TS"
# Time-series parameters:
TS:
  porto:
    format: ".csv"
    K: 365 # seasonal period: 365 (1 year)
    U: 20 # rolling window iterations: 20
    W: 1825 # Window - data size per iterarion: 1825 (5 years)
    H: 30 # time-ahead predictions
    target: "tempC" # target column
    WR: [1, 365, 366, 730, 731] # lag window for regression dataset creation
  lisbon:
    format: ".csv"
    K: 365 # seasonal period: 365 (1 year)
    U: 20 # rolling window iterations: 20
    W: 1825 # Window - data size per iterarion: 10825 (5 years)
    H: 30 # time-ahead predictions
    target: "tempC" # target column
    WR: [1, 365, 366, 730, 731] # lag window for regression dataset creation
# Models parameters:
MODELS:
  fedot:
    timeout: 15 # 15min for automl
  sktime:
    sp: 7 # seasonal period

