# Data Directories:
DATA_PATH: "../data"
RAW_PATH: "1_raw"
PREP_PATH: "2_preprocessed"
MODELS_PATH: "3_models"
PRED_PATH: "4_predictions"
RES_PATH: "5_results"
MLFLOW_PATH: "mlflow/mlruns"

# ML FLOW
EXPERIMENT: "Benchmark TS"
# Time-series parameters:
TS:
  porto:
    format: ".csv"
    K: 7 # seasonal period: 7 (week?)
    U: 5 # rolling window iterations: 5 (?)
    W: 1825 # Window - data size per iterarion: 1825 (5 years?)
    H: 30 # time-ahead predictions
    target: "tempC" # target column
  lisbon:
    format: ".csv"
    K: 7 # seasonal period: 7 (week?)
    U: 5 # rolling window iterations: 5 (?)
    W: 1825 # Window - data size per iterarion: 1825 (5 years?)
    H: 30 # time-ahead predictions
    target: "tempC" # target column
LR:
  iterations: 1000
